config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    omniauth_callbacks: 'omniauth_callbacks'
  }

  devise_scope :user do
    get '/users/sign_out' => 'devise/sessions#destroy'
  end

  namespace :admin do
    devise_scope :user do
      get 'login', to: 'sessions#new'
      post 'login', to: 'sessions#create'
      delete 'logout', to: 'sessions#destroy'
    end
    root to: 'dashboards#index'
    resources :users, only: %i[index show edit update destroy]
    resources :posts, only: %i[index show edit update destroy]
  end

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root 'top#index'
  get 'terms', to: 'top#terms'
  get 'privacy', to: 'top#privacy'
  get 'contact', to: 'top#contact'

  get 'search' => 'posts#search'

  resources :users, only: %i[index new create show]
  resources :password_resets, only: %i[new create edit update]
  resource :my_page, only: %i[show]
  resources :posts do
    resources :comments, only: %i[create destroy], shallow: true
    member do
      get :likes
    end
  end
  resources :likes, only: %i[create destroy]
  resource :profile, only: %i[show edit update]
  resources :records, only: %i[index update]
  get 'reset_records', to: 'records#reset_records', as: :reset_records
  resources :targets, only: %i[new create edit update]
  resources :notifications, only: %i[index]
  resources :savings_items, only: %i[new create edit update]
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :post
  
  validates :content, presence: true, length: { maximum: 65_535 }
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :authenticate_user!

  def create
    @post = Post.find(params[:post_id])
    @comment = current_user.comments.build(comment_params)
    @comment.post = @post
    @comment.save
  end

  def destroy
    @comment = current_user.comments.find(params[:id])
    @comment.destroy!
  end

  private

  def comment_params
    params.require(:comment).permit(:content).merge(post_id: params[:post_id])
  end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/comments/_comment.html.erb
<tr id="comment-<%= comment.id %>">
  <td style="width: 60px">
    <%= image_tag comment.user.avatar_url, class: 'rounded-circle', size: '50x50' %>
  </td>
  <td>
    <% user = comment.user %>
      <%= link_to user_path(user), class: "edit-link" do %>
        <h3 class="small"><%= user.decorate.name %></h3>
      <% end %>
    <div id="js-comment-<%= comment.id %>">
      <%= simple_format(comment.content) %>
    </div>
    <div id="js-textarea-comment-box-<%= comment.id %>" style="display: none;">
      <textarea id="js-textarea-comment-<%= comment.id %>" class="form-control mb-1"><%= comment.content %></textarea>
      <button class="btn btn-light js-button-edit-comment-cancel" data-comment-id="<%= comment.id %>">キャンセル</button>
      <button class="btn btn-success js-button-comment-update" data-comment-id="<%= comment.id %>">更新</button>
    </div>
  </td>
  <% if current_user.own?(comment) %>
    <td class="action">
      <ul class="list-inline justify-content-center" style="float: right;">
        <li class="list-inline-item">
          <%= link_to comment_path(comment), class: 'js-delete-comment-button', id: "button-delete-#{comment.id}", data: { turbo_method: :delete }, onclick: "return confirm('投稿を削除しますか？');" do %>
            <%= icon 'fa', 'trash' %>
          <% end %>
        </li>
      </ul>
    </td>
  <% end %>
</tr>

app/views/comments/_comments.html.erb
<div class="row">
  <div class="col-lg-8 offset-lg-2">
    <table id="js-table-comment" class="table">
      <%= render comments %>
    </table>
  </div>
</div>

app/views/comments/_form.html.erb
<div class="row mb-3">
  <div class="col-lg-8 offset-lg-2">
    <%= form_with model: comment, url: [post, comment], id: 'new_comment' do |f| %>
      <%= render 'shared/error_messages', object: f.object %>
      <%= f.text_area :content, class: 'form-control mb-3', id: 'js-new-comment-content', row: 4, placeholder: Comment.human_attribute_name(:content) %>
      <%= f.submit 'コメントする', class: "btn btn-secondary search-btn" %>
    <% end %>
  </div>
</div>

app/views/comments/create.js.erb
$("#error_messages").remove()
<% if @comment.errors.present? %>
  $("#new_comment").prepend("<%= j(render('shared/error_messages', object: @comment)) %>")
<% else %>
  $("#js-table-comment").prepend("<%= j(render('comments/comment', comment: @comment)) %>")
  $("#js-new-comment-content").val('')
<% end %>

app/views/comments/destroy.js.erb
$("tr#comment-<%= @comment.id %>").remove()