config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    omniauth_callbacks: 'omniauth_callbacks'
  }

  devise_scope :user do
    get '/users/sign_out' => 'devise/sessions#destroy'
  end

  namespace :admin do
    devise_scope :user do
      get 'login', to: 'sessions#new'
      post 'login', to: 'sessions#create'
      delete 'logout', to: 'sessions#destroy'
    end
    root to: 'dashboards#index'
    resources :users, only: %i[index show edit update destroy]
    resources :posts, only: %i[index show edit update destroy]
  end

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root 'top#index'
  get 'terms', to: 'top#terms'
  get 'privacy', to: 'top#privacy'
  get 'contact', to: 'top#contact'

  get 'search' => 'posts#search'

  resources :users, only: %i[index new create show]
  resources :password_resets, only: %i[new create edit update]
  resource :my_page, only: %i[show]
  resources :posts do
    resources :comments, only: %i[create destroy], shallow: true
    member do
      get :likes
    end
  end
  resources :likes, only: %i[create destroy]
  resource :profile, only: %i[show edit update]
  resources :records, only: %i[index update]
  get 'reset_records', to: 'records#reset_records', as: :reset_records
  resources :targets, only: %i[new create edit update]
  resources :notifications, only: %i[index]
  resources :savings_items, only: %i[new create edit update]
end

app/views/shared/_before_login_header.html.erb
<header>
  <div class="main-menu">
    <%= link_to root_path,class: "edit-link" do %>
      <%= image_tag 'logo.png', class: 'img-fluid mx-auto d-block' %>
    <% end %>
    </div>
    <div class="pc-menu">
      <ul>
        <li>
          <%= link_to (t 'defaults.login'), user_session_path %>
        </li>
      </ul>
    </div>
    <div class="sp-menu">
      <input type="checkbox" id="sp-menu__check">
      <label for="sp-menu__check" class="sp-menu__box">
        <span></span>
      </label>
      <div class="sp-menu__content">
        <ul class="sp-menu__list">
          <li class="sp-menu__item">
            <%= link_to (t 'defaults.login'), user_session_path, class: "sp-menu__link" %>
          </li>
        </ul>
      </div>
    </div>
  </div>
</header>

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
  <div id="error_messages" class="alert alert-danger">
    <ul class="mb-0">
      <% object.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_flash_message.html.erb
<% flash.each do |message_type, message| %>
  <div class="alert alert-<%= message_type %>"><%= message %></div>
<% end %>

app/views/shared/_footer.html.erb
<footer class="footer">
  <div class="container-fluid">
    <ul class="nav justify-content-center">
      <li class="nav-item">
        <%= link_to "利用規約", terms_path, class: 'nav-link text-dark fw-bold' %>
      </li>
      <li class="nav-item">
        <%= link_to "プライバシーポリシー", privacy_path, class: 'nav-link text-dark fw-bold' %>
      </li>
      <li class="nav-item">
        <%= link_to "お問い合わせ", "https://forms.gle/vc8USid8nAuv2S3o9", class: 'nav-link text-dark fw-bold' %>
      </li>
    </ul>
    <div class="mt-4">
      <p class="text-center text-muted">Copyright © 2023. ちりつも節約</p>
    </div>
  </div>
</footer>

app/views/shared/_header.html.erb
<header>
  <div class="main-menu">
    <%= link_to root_path,class: "edit-link" do %>
      <%= image_tag 'logo.png', class: 'img-fluid mx-auto d-block' %>
    <% end %>
    <div class="pc-menu">
      <ul>
        <li class="left-aligned-link">
          <%= link_to posts_path do %>
            <i class="far fa-folder-open"></i>
            <%= (t 'defaults.posts') %>
          <% end %>
        </li>
        <li class="left-aligned-link">
          <%= link_to users_path do %>
            <i class="fas fa-chess-queen"></i>
            <%= (t 'defaults.user_list') %>
          <% end %>
        </li>
        <li class="left-aligned-link">
          <%= link_to records_path do %>
            <i class="fas fa-pen"></i>
            <%= (t 'defaults.record') %>
          <% end %>
        </li>
        <li class="user-menu">
          <div class="user-image">
            <%= link_to '#', class: 'dropdown-trigger' do %>
              <%= image_tag current_user.avatar.url, class: 'rounded-circle', size: '50x50', alt: "User Avatar" %>
            <% end %>
          </div>
          <div class="user-dropdown">
            <div class="user-name">
              <%= link_to profile_path do %>
                <%= current_user.decorate.name %>
              <% end %>
            </div>
            <%= link_to (t 'defaults.my_page'), my_page_path %>
            <% if current_user.target %>
              <%= link_to (t 'defaults.target_edit'), edit_target_path(current_user.target) %>
            <% else %>
              <%= link_to (t 'defaults.target'), new_target_path %>
            <% end %>
            <%= link_to t('defaults.logout'), destroy_user_session_path, method: :delete, onclick: "return confirm('ログアウトしますか？');" %>
            <a href="https://lin.ee/YGnyorU"><img src="https://scdn.line-apps.com/n/line_add_friends/btn/ja.png" alt="友だち追加" height="36" border="0"></a>
          </div>
        </li>
      </ul>
    </div>
    <div class="sp-menu">
      <input type="checkbox" id="sp-menu__check">
      <label for="sp-menu__check" class="sp-menu__box">
        <span></span>
      </label>
      <div class="sp-menu__content">
        <ul class="sp-menu__list">
          <li class="sp-menu__item">
            <%= link_to (t 'defaults.posts'), posts_path, class: "sp-menu__link" %>
          </li>
          <li class="sp-menu__item">
            <%= link_to (t 'defaults.my_page'), my_page_path, class: "sp-menu__link" %>
          </li>
          <li class="sp-menu__item">
            <%= link_to (t 'defaults.user_list'), users_path, class: "sp-menu__link" %>
          </li>
          <li class="sp-menu__item">
            <%= link_to (t 'defaults.record'), records_path, class: "sp-menu__link" %>
          </li>
          <li class="sp-menu__item">
            <% if current_user.target %>
              <%= link_to (t 'defaults.target_edit'), edit_target_path(current_user.target), class: "sp-menu__link" %>
            <% else %>
              <%= link_to (t 'defaults.target'), new_target_path, class: "sp-menu__link" %>
            <% end %>
          </li>
          <li class="sp-menu__item">
              <%= link_to t('defaults.logout'), destroy_user_session_path, method: :delete, onclick: "return confirm('ログアウトしますか？');", class: "sp-menu__link" %>
          </li>
          <li class="sp-menu__item">
              <a href="https://lin.ee/YGnyorU"><img src="https://scdn.line-apps.com/n/line_add_friends/btn/ja.png" alt="友だち追加" height="36" border="0"></a>
          </li>
        </ul>
      </div>
    </div>
  </div>
</header>