config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    omniauth_callbacks: 'omniauth_callbacks'
  }

  devise_scope :user do
    get '/users/sign_out' => 'devise/sessions#destroy'
  end

  namespace :admin do
    devise_scope :user do
      get 'login', to: 'sessions#new'
      post 'login', to: 'sessions#create'
      delete 'logout', to: 'sessions#destroy'
    end
    root to: 'dashboards#index'
    resources :users, only: %i[index show edit update destroy]
    resources :posts, only: %i[index show edit update destroy]
  end

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root 'top#index'
  get 'terms', to: 'top#terms'
  get 'privacy', to: 'top#privacy'
  get 'contact', to: 'top#contact'

  get 'search' => 'posts#search'

  resources :users, only: %i[index new create show]
  resources :password_resets, only: %i[new create edit update]
  resource :my_page, only: %i[show]
  resources :posts do
    resources :comments, only: %i[create destroy], shallow: true
    member do
      get :likes
    end
  end
  resources :likes, only: %i[create destroy]
  resource :profile, only: %i[show edit update]
  resources :records, only: %i[index update]
  get 'reset_records', to: 'records#reset_records', as: :reset_records
  resources :targets, only: %i[new create edit update]
  resources :notifications, only: %i[index]
  resources :savings_items, only: %i[new create edit update]
end

app/models/record.rb
class Record < ApplicationRecord
  belongs_to :user
  belongs_to :savings_item, optional: true # nil のままでも保存が可能
  include SharedConstants

  scope :for_month, ->(month) { where(created_at: month.beginning_of_month..month.end_of_month) }

  def self.calculate_monthly_records(user)
    user.records.group_by { |record| record.created_at.beginning_of_month }.map do |month, records_in_month|
      monthly_total_savings = calculate_savings(records_in_month)
      {
        month: month.strftime('%Y-%m'),
        total_savings: monthly_total_savings,
        monthly_records: records_in_month
      }
    end
  end

  def self.calculate_savings(records)
    total_savings = 0

    records.each do |record|
      total_savings += record.savings_item.amount if record.savings_item.present?
      total_savings += ITEM_PRICES[:bottle_bring] if record.bottle_bring
      total_savings += ITEM_PRICES[:packed_lunch] if record.packed_lunch
      total_savings += ITEM_PRICES[:alternative_transportation] if record.alternative_transportation
      total_savings += ITEM_PRICES[:no_eating_out] if record.no_eating_out
    end

    total_savings
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable,
         :omniauthable, omniauth_providers: %i[line]

  mount_uploader :avatar, AvatarUploader

  has_many :posts, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :likes
  has_many :like_posts, through: :likes, source: :post
  has_many :records
  has_many :targets, dependent: :destroy
  has_many :savings_items, dependent: :destroy
  has_one :target

  validates :name, presence: true, length: { maximum: 20 }

  enum role: { general: 0, admin: 1 }

  attr_accessor :rank, :rank_value, :monthly_rank, :monthly_rank_value

  def social_profile(provider)
    social_profiles.select { |sp| sp.provider == provider.to_s }.first
  end

  def set_values(omniauth)
    return if provider.to_s != omniauth['provider'].to_s || uid != omniauth['uid']

    credentials = omniauth['credentials']
    info = omniauth['info']

    access_token = credentials['refresh_token']
    access_secret = credentials['secret']
    credentials = credentials.to_json
    name = info['name']
  end

  def set_values_by_raw_info(raw_info)
    self.raw_info = raw_info.to_json
    save!
  end

  def own?(object)
    id == object.user_id
  end

  def like(post)
    like_posts << post
  end

  def unlike(post)
    like_posts.destroy(post)
  end

  def like?(post)
    like_posts.include?(post)
  end

  def result
    total_savings = calculate_savings(records)

    {
      total_savings:
    }
  end

  def total_savings
    calculate_savings(records)
  end

  def calculate_monthly_records_for_user(records_in_month)
    calculate_savings(records_in_month)
  end

  def calculate_savings(records)
    total_savings = 0

    records.each do |record|
      total_savings += calculate_record_savings(record)
    end

    total_savings
  end

  def calculate_record_savings(record)
    total_savings = 0

    total_savings += record.savings_item.amount if record.savings_item.present?
    total_savings += item_prices[:bottle_bring] if record.bottle_bring
    total_savings += item_prices[:packed_lunch] if record.packed_lunch
    total_savings += item_prices[:alternative_transportation] if record.alternative_transportation
    total_savings += item_prices[:no_eating_out] if record.no_eating_out

    total_savings
  end

  def savings_category_and_image
    total_savings = calculate_savings(records)

    if total_savings.between?(0, 3000)
      category = '節約駆け出し'
      image = 'avatar1.png'
    elsif total_savings.between?(3001, 8000)
      category = '節約ハンター'
      image = 'avatar2.png'
    elsif total_savings.between?(8001, 13000)
      category = '節約探検家'
      image = 'avatar3.png'
    elsif total_savings.between?(13001, 17000)
      category = '節約キング'
      image = 'avatar4.png'
    else
      category = '節約マスター'
      image = 'avatar5.png'
    end

    { category: category, image: image }
  end

  def item_prices
    SharedConstants::ITEM_PRICES
  end

  def target_amount
    target = self.target
    target&.target_amount
  end
end

app/controllers/records_controller.rb
class RecordsController < ApplicationController
  before_action :authenticate_user!

  def index
    @records = current_user.records
    @savings = current_user.total_savings
    @result = current_user.result
    @monthly_records = Record.calculate_monthly_records(current_user)
    @today_records = current_user.records.where('created_at >= ?', Time.zone.now.beginning_of_day)
    @show_record_form = @today_records.empty?
    @savings_items = current_user.savings_items
  end

  def update
    today_records = current_user.records.where('created_at >= ?', Time.zone.now.beginning_of_day)

    return unless today_records.empty?

    ActiveRecord::Base.transaction do
      @record = current_user.records.new(record_params)

      selected_savings_items = current_user.savings_items.where(id: params.dig(:record, :savings_item_ids))
      @record.savings_item = selected_savings_items.first if selected_savings_items.present?
      @record.savings_item = nil if selected_savings_items.empty?  # Add this line

      @savings = current_user.calculate_record_savings(@record)

      unless @record.save
        logger.debug @record.errors.full_messages
        raise ActiveRecord::Rollback
      end

      @user_records = current_user.records
      @result = current_user.result

      flash[:success] = t('defaults.message.updated', item: Record.model_name.human)

      flash[:success] = t('defaults.message.target_money_achievement') if reached_target_amount?
    end

    redirect_to records_path
  end

  private

  def record_params
    params.fetch(:record, {}).permit(:bottle_bring, :packed_lunch, :alternative_transportation, :no_eating_out)
  end

  def reached_target_amount?
    target_amount = current_user.target_amount
    target_amount && @savings >= target_amount
  end
end

app/helpers/records_helper.rb
module RecordsHelper
end

app/views/records/index.html.erb
<div class="background-image">
  <div class="content">
    <% if @show_record_form %>
    <h1><%= t('.title') %></h1>
      <%= form_with(model: @records, url: record_path(@records), method: :patch) do |form| %>
        <table>
          <tbody>
            <tr>
              <td>
                <div class="item">
                  1, 外出時、マイボトルを持参した
                </div>
              </td>
              <td>
                <span style="white-space: nowrap;">100円</span>
              </td>
              <td>
                <div class="checkbox-wrapper">
                  <%= check_box_tag 'record[bottle_bring]' %>
                </div>
              </td>
            </tr>
            <tr>
              <td>
                <div class="item">
                  2, お昼ご飯を弁当持参、または自炊した
                </div>
              </td>
              <td>
                <span style="white-space: nowrap;">300円</span>
              </td>
              <td>
                <div class="checkbox-wrapper">
                  <%= check_box_tag 'record[packed_lunch]' %>
                </div>
              </td>
            </tr>
            <tr>
              <td>
                <div class="item">
                  3, 交通手段を徒歩、または自転車を利用した
                </div>
              </td>
              <td>
                <span style="white-space: nowrap;">200円</span>
              </td>
              <td>
                <div class="checkbox-wrapper">
                  <%= check_box_tag 'record[alternative_transportation]' %>
                </div>
              </td>
            </tr>
            <tr>
              <td>
                <div class="item">
                  4, コンビニに行かなかった
                </div>
              </td>
              <td>
                <span style="white-space: nowrap;">300円</span>
              </td>
              <td>
                <div class="checkbox-wrapper">
                  <%= check_box_tag 'record[no_eating_out]' %>
                </div>
              </td>
            </tr>
            <% latest_savings_item_created_at = current_user.savings_items.order(created_at: :desc).limit(1).pluck(:created_at).first %>
            <% @savings_items.each do |savings_item| %>
              <% if savings_item.created_at == latest_savings_item_created_at %>
                <tr>
                  <td>
                    <div class="item">
                      <span class="star">&#9733;</span>
                        <%= savings_item.name %>
                    </div>
                  </td>
                  <td>
                    <span style="white-space: nowrap;"><%= savings_item.amount %>円</span>
                  </td>
                  <td>
                    <div class="checkbox-wrapper">
                      <%= check_box_tag "record[savings_item_ids][]", savings_item.id %>
                    </div>
                  </td>
                </tr>
              <% end %>
            <% end %>

          </tbody>
        </table>
        <%= form.submit '更新' %>
        <div class="item">
          <p><%= t('.total_savings') %><%= @savings %>円</p>
        </div>
      <% end %>
    <% else %>
      <p><%= t('.record_already_made') %></p>
      <p><%= t('.record_tomorrow') %></p>
      <div class="item">
          <p><%= t('.total_savings') %><%= @savings %>円</p>
      </div>
    <% end %>
      <div class="savings-category">
        <% category_and_image = current_user.savings_category_and_image %>
        <img src="<%= asset_path(category_and_image[:image]) %>" alt="<%= category_and_image[:category] %>">
        <br>
        <br>
        <p><%= category_and_image[:category] %></p>
      </div>
      <div class="item">
        <% if @show_record_form && @savings_items.empty? %>
          <!-- 節約項目作成のリンクを表示 -->
          <%= button_to t('.create_savings_item'), new_savings_item_path, method: :get, class: 'edit-link' %>
        <% elsif !@savings_items.empty? %>
          <!-- 節約項目編集のリンクを表示 -->
          <%= button_to t('.edit_savings_item'), edit_savings_item_path(@savings_items.first), method: :get %>
        <% end %>
      </div>
    <br>
    <div class="past-records">
      <h2><%= t('.past_record') %></h2>
      <br>
      <table>
        <thead>
          <tr>
            <th><%= t('.year_month') %></th>
            <th><%= t('.save_money') %></th>
          </tr>
        </thead>
        <tbody>
          <% @monthly_records.each do |record| %>
            <tr>
              <td><%= record[:month] %></td>
              <td><%= record[:total_savings] %>円</td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>