config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    omniauth_callbacks: 'omniauth_callbacks'
  }

  devise_scope :user do
    get '/users/sign_out' => 'devise/sessions#destroy'
  end

  namespace :admin do
    devise_scope :user do
      get 'login', to: 'sessions#new'
      post 'login', to: 'sessions#create'
      delete 'logout', to: 'sessions#destroy'
    end
    root to: 'dashboards#index'
    resources :users, only: %i[index show edit update destroy]
    resources :posts, only: %i[index show edit update destroy]
  end

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root 'top#index'
  get 'terms', to: 'top#terms'
  get 'privacy', to: 'top#privacy'
  get 'contact', to: 'top#contact'

  get 'search' => 'posts#search'

  resources :users, only: %i[index new create show]
  resources :password_resets, only: %i[new create edit update]
  resource :my_page, only: %i[show]
  resources :posts do
    resources :comments, only: %i[create destroy], shallow: true
    member do
      get :likes
    end
  end
  resources :likes, only: %i[create destroy]
  resource :profile, only: %i[show edit update]
  resources :records, only: %i[index update]
  get 'reset_records', to: 'records#reset_records', as: :reset_records
  resources :targets, only: %i[new create edit update]
  resources :notifications, only: %i[index]
  resources :savings_items, only: %i[new create edit update]
end

app/models/post.rb
class Post < ApplicationRecord
  mount_uploader :post_image, PostImageUploader
  belongs_to :user
  has_many :comments, dependent: :destroy
  has_many :likes, dependent: :destroy
  has_many :liked_users, through: :likes, source: :user
  has_many :association_post_and_tags, dependent: :destroy
  has_many :tags, through: :association_post_and_tags

  validates :title, presence: true, length: { maximum: 50 }
  validates :content, presence: true, length: { maximum: 65_535 }

  scope :latest, -> { order(created_at: :desc) }
  scope :old, -> { order(created_at: :asc) }
  scope :most_liked, lambda {
                       includes(:liked_users)
                         .sort_by { |x| x.liked_users.includes(:likes).size }.reverse
                     }

  def self.search(keyword)
    where('title LIKE ? or content LIKE ?', "%#{sanitize_sql_like(keyword)}%", "%#{sanitize_sql_like(keyword)}%")
  end

  def self.sort_and_paginate(params)
    posts = all
    posts = Tag.find(params[:tag_id]).posts if params[:tag_id].present?

    posts = posts.search(params[:keyword]) if params[:keyword].present?

    posts = case params[:sort_order]
            when 'latest'
              posts.sort_by { |post| post.created_at }.reverse
            when 'old'
              posts.sort_by { |post| post.created_at }
            when 'most_liked'
              posts.sort_by { |post| -post.liked_users.size }
            else
              posts.sort_by { |post| post.created_at }.reverse
            end

    Kaminari.paginate_array(posts).page(params[:page]).per(10)
  end
end

app/controllers/admin/posts_controller.rb
class Admin::PostsController < Admin::BaseController
  skip_before_action :check_admin
  before_action :set_posts, only: %i[show edit update destroy]

  def index
    @posts = Post.includes(:user).order(created_at: :desc)
  end

  def show
    @post = Post.find(params[:id])
  end

  def edit; end

  def update
    if @post.update(post_params)
      redirect_to admin_posts_path(@post), success: t('defaults.message.updated', item: Post.model_name.human)
    else
      flash.now[:danger] = t('defaults.message.not_updated', item: Post.model_name.human)
      render :edit
    end
  end

  def destroy
    @post.destroy!
    redirect_to admin_posts_path, success: t('defaults.message.deleted', item: Post.model_name.human)
  end

  private

  def set_posts
    @post = Post.find(params[:id])
  end
  

  def post_params
    params.require(:post).permit(:title, :content, :post_image, :post_image_cache, tag_ids: [])
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def index
    set_posts
    case params[:sort_order]
    when 'latest'
      flash.now[:success] = t('defaults.message.latest')
    when 'old'
      flash.now[:success] = t('defaults.message.old')
    when 'most_liked'
      flash.now[:success] = t('defaults.message.most_liked')
    end
  end

  def new
    @post = Post.new
  end

  def create
    @post = current_user.posts.build(post_params)
    if @post.save
      redirect_to posts_path, success: t('defaults.message.created', item: Post.model_name.human)
    else
      flash.now['danger'] = t('defaults.message.not_created', item: Post.model_name.human)
      render :new
    end
  end

  def show
    @post = Post.find(params[:id])
    @comment = Comment.new
    @comments = @post.comments.includes(:user).order(created_at: :desc)
  end

  def edit
    @post = current_user.posts.find(params[:id])
  end

  def update
    @post = current_user.posts.find(params[:id])
    if @post.update(post_params)
      redirect_to @post, success: t('defaults.message.updated', item: Post.model_name.human)
    else
      flash.now['danger'] = t('defaults.message.not_updated', item: Post.model_name.human)
      render :edit
    end
  end

  def destroy
    @post = Post.find(params[:id])
    @post.destroy
    redirect_to my_page_path, status: :see_other, success: t('defaults.message.deleted', item: Post.model_name.human)
  end

  def likes
    @like_posts = current_user.likes.includes(:post, :user).order(created_at: :desc)
  end

  private

  def post_params
    params.require(:post).permit(:title, :content, :post_image, :post_image_cache, tag_ids: [])
  end

  def set_posts
    @posts = Post.sort_and_paginate(params)
  end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/_crud_menus.html.erb
<ul class='crud-menu-btn list-inline float-right'>
  <li class="list-inline-item">
    <%= link_to edit_post_path(post), id: "button-edit-#{post.id}" do %>
      <%= icon 'fa', 'pen' %>
    <% end %>
  </li>
  <li class="list-inline-item">
    <%= link_to post_path(post), id: "button-delete-#{post.id}", data: { turbo_method: :delete }, onclick: "return confirm('投稿を削除しますか？');" do %>
      <%= icon 'fas', 'trash' %>
    <% end %>
  </li>
</ul>

app/views/posts/_form.html.erb
<%= form_with model: post, local: true do |f| %>
  <%= render 'shared/error_messages', object: f.object %>
  <div class="container mt-5">
    <div class="row">
      <div class="form-group col-auto">
        <%= f.label :tag %>
        <div class="form-control">
          <% Tag.all.each do |tag| %>
            <div class="form-check form-check-inline">
              <%= check_box_tag "post[tag_ids][]", tag.id, @post.tag_ids.include?(tag.id), id: "tag_#{tag.id}", class: "form-check-input" %>
              <%= label_tag "tag_#{tag.id}", tag.tag_type, class: "form-check-label" %>
            </div>
          <% end %>
        </div>
      </div>
    </div>
    <div>
      <div class="form-group mt-4 mb-2">
        <%= f.label :title %>
        <span class="badge text-bg-danger">必須</span>
        <%= f.text_field :title, class: 'form-control' %>
      </div>
      <div class="form-group my-2">
        <%= f.label :content %>
        <span class="badge text-bg-danger">必須</span>
        <%= f.text_area :content, class: 'form-control' %>
      </div>
      <div class="form-group my-2">
        <%= f.label :post_image %>
        <%= f.file_field :post_image, class: 'form-control mb-5', accept: 'image/*' %>
        <%= f.hidden_field :post_image_cache %>
      </div>

      <%= f.submit '投稿する', class: 'btn btn-light mb-3' %>
    </div>
  </div>
<% end %>

app/views/posts/_like.html.erb
<%= link_to likes_path(post_id: post.id),
            id: "js-like-button-for-post-#{post.id}",
            class: "like-link",
            data: { "turbo-method": :post },
            remote: true do %>
  <i class="fa fa-heart like-btn"></i>
<% end %>
<%= post.likes.count %>

app/views/posts/_like_button.html.erb
<% if current_user.like?(post) %>
  <%= render 'unlike', { post: post } %>
<% else %>
  <%= render 'like', { post: post } %>
<% end %>

app/views/posts/_post.html.erb
<div class="card-deck">
  <div class="card mb-2 h-100" style="background-color: rgb(255, 255, 255); border: 1px solid #bfbebe; padding: 10px; box-shadow: inset 0 0 10px 10px rgba(156, 87, 27, 0.5);">
    <div class="post-image">
      <div class="row g-0">
        <div class="col-md-4 p-md-2">
          <%= image_tag post.post_image_url, class: 'card-img-top', size: '200x200' %>
        </div>
        <div class="col-md-8">
          <div class="card-body">
            <div class="d-flex flex-column h-100">
              <%= link_to post.title, post_path(post), class: "post-title card-title" %>
              <h2 class="card-text small-text d-none d-md-block">
                <%= truncate(post.content, length: 80) %>
              </h2>
              <h2 class="card-text small-text d-block d-md-none">
                <%= truncate(post.content, length: 50) %>
              </h2>
              <div class="post-info post-info-bottom-right">
                <div class="d-md-block">
                  <% post.tags.each do |tag| %>
                    <span class="badge bg-primary"><%= tag.tag_type %></span>
                  <% end %>
                </div>
                <ul class="list-inline mt-2">
                  <li class="list-inline-item">
                    <%= icon 'far', 'user' %>
                    <%= post.user.decorate.name %>
                    <%= l post.created_at, format: :long %>
                  </li>
                </ul>
                <% if current_user.own?(post) %>
                  <%= render 'crud_menus', post: post %>
                <% else %>
                  <%= render 'like_button', post: post  %>
                <% end %>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/posts/_search.html.erb
<div class="search-background">
  <div class="d-flex justify-content-end my-2">
    <div class="input-group">
      <%= button_to (t 'defaults.post'), new_post_path, method: :get, class: "form-control ml-auto small" %>
      <%= form_with url: posts_path, method: :get, local: true, class: 'boards__searchForm flex-fill' do |f|%>
        <div class="input-group">
          <%= f.text_field :keyword, value: @keyword, class: "form-control search-control", placeholder: "キーワードを入力" %>
          <%= select_tag :tag_id,
            options_from_collection_for_select(Tag.all, :id, :tag_type, params[:tag_id]),
              {
                prompt: "タグで絞り込み検索",
                onchange: "submit(this.form);",
                class: "form-control search-control small"
              }
          %>
          <%= select_tag :sort_order,
            options_for_select({
              "新着順": "latest",
              "古い順": "old",
              "いいね順": "most_liked"
            }, params[:sort_order]),
            {
              prompt: "ソート順を選択",
              onchange: "submit(this.form);",
              class: "form-control search-control small"
            }
          %>
          <span class="input-group-append">
            <%= button_tag type: "submit", class: "btn btn-secondary search-btn" do %>
              <i class="fas fa-search"></i> 検索
            <% end %>
          </span>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/posts/_unlike.html.erb
<%= link_to like_path(current_user.likes.find_by(post_id: post.id)),
            id: "js-like-button-for-post-#{post.id}",
            class: "like-link",
            data: { "turbo-method": :delete },
            remote: true do %>
  <i class="fa fa-heart unlike-btn"></i>
<% end %>
<%= post.likes.count %>

app/views/posts/edit.html.erb
<div class="background-image">
  <div class="container pt-4">
    <div class="row">
      <div class="col-md-11 col-lg-7 mx-auto">
        <div class="card shadow">
          <div class="card-body p-4 p-sm-5">
            <p class='text-center mb-4 fw-light fs-2'><%= t('.title') %></p>
            <%= render 'form', { post: @post } %>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/posts/index.html.erb
<div class="container-fluid" style="font-family: 'arial unicode ms'; background-color: rgb(232, 239, 204);">
  <div class="row">
    <div class="col-12">
      <br>
      <br>
      <div class="post-page">
        <%= t('.title') %>
      </div>
      <br>
      <br>
      <br>
      <%= render "search", post: @post %>
      <br>
      <div class="row row-cols-md-2 g-2">
        <% if @posts.present? %>
          <%= render @posts %>
        <% else %>
          <p><%= t('.no_result') %></p>
        <% end %>
      </div>
    </div>
    <div class="d-flex justify-content-center mt-5">
      <%= paginate @posts, theme: 'bootstrap-5' %>
    </div>
  </div>
</div>

app/views/posts/new.html.erb
<div class="background-image">
  <div class="container pt-4">
    <div class="row">
      <div class="col-md-11 col-lg-7 mx-auto">
        <div class="card shadow">
          <div class="card-body p-4 p-sm-5">
            <p class='text-center mb-4 fw-light fs-2'><%= t('.title') %></p>
            <%= render 'form', { post: @post } %>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/posts/show.html.erb
<body class="background-image">
  <div class="container pt-5 mb-5 mt-3">
    <div class="row mb-3">
      <div class="col-lg-8 offset-lg-2 mb-3 border p-4 bg-light">
        <article class="card">
          <div class="card-body">
            <div class='row'>
              <div class='col-12'>
                <%= image_tag @post.post_image_url, class: 'card-img-top img-fluid', size: '300x200' %>
              </div>
              <div class='col-12'>
                <br>
                <h3 style='display: inline;'><%= @post.title %></h3>
                <% if current_user.own?(@post) %>
                  <%= render 'crud_menus', post: @post %>
                  <%= render 'like_button', post: @post  %>
                <% else %>
                  <br>
                  <br>
                  <%= render 'like_button', post: @post  %>
                <% end %>
                <% @post.tags.each do |tag| %>
                      <span class="badge bg-primary"><%= tag.tag_type %></span>
                <% end %>
                <ul class="list-inline">
                <br>
                  <li class="list-inline-item">
                    <%= link_to user_path(@post.user), class: "edit-link" do %>
                      <%= image_tag @post.user.avatar.url, class: 'rounded-circle', size: '40x40' %>
                      <%= @post.user.decorate.name %>
                    <% end %>
                  </li>
                  <li class="list-inline-item"><%= l @post.created_at, format: :long %></li>
                </ul>
              </div>
            </div>
            <div class="card">
            <p><%= simple_format(@post.content) %></p>
            </div>
            <br>
          </div>
        </article>
      </div>
    </div>
  </div>
  <div class="container">
    <% if current_user %>
      <%= render 'comments/form', { post: @post, comment: @comment } %>
    <% end %>
      <%= render 'comments/comments', { comments: @comments } %>
  </div>
</body>